create database employee_management;

CREATE TYPE DESIGNATION_TYPE AS ENUM('PROGRAMMAR', 'TESTER', 'ADMIN', 'MANAGER');

CREATE TABLE EMPLOYEE (
	EID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	AGE SMALLINT NOT NULL CHECK (
		AGE > 20
		AND AGE <= 60
	),
	SALARY DECIMAL(9, 2),
	DESIGNATION DESIGNATION_TYPE NOT NULL,
);